### ISSUE TITLE
Zack's Questions

### ISSUE THREAD

**Issue by zwhile** [lhnealreilly/final-puzzle-cs-191#7]
The prompt is pretty straight-forward and clear so I don't have any clarifications with that.  I guess a more theoretical question: Is there only 1 possible ~~shape~~ triangle you can make with these (with the given rules)?  If there's only one possible ~~shape~~ triangle, it's probably not too difficult to prove.  (Not forcing you here to give a proof, but I'm curious if the solution you found/made only presents one solution).

I don't look at the solutions until I add my solution, so I'm not sure if there are multiple possible answers.

**Comment by PogDave** [comment]
The main idea/task of the puzzle is to use all the 5 parts of the rectangle to create 1 triangle, I think we forgot to mention this rule. Hope this clarifies your issue.
